backend:
  name: github
  repo: Benzio/gridsome-starter-blog
  publish_mode: editorial_workflow

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    filter:
      field: published
      value: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Cover Image", name: "cover_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
